# Generated by Django 4.1.7 on 2026-08-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transtaction_id',
            new_name='transaction_id',
        ),
    ]
