# Generated by Django 4.1.7 on 2026-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='mail',
            field=models.EmailField(default='guest@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
