# Generated by Django 4.1.7 on 2026-08-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contactmessage_mail_contactmessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
