# Generated by Django 4.1.7 on 2026-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_contactmessage_mail_alter_contactmessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='S, M, L, XL, XXL', max_length=100),
        ),
    ]
