# Generated by Django 4.1.7 on 2026-08-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='S M L XL XXL', max_length=100),
        ),
    ]
