# Generated by Django 4.1.7 on 2026-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_order_product_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
