# Generated by Django 4.1.7 on 2026-08-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
