# Generated by Django 4.1.7 on 2026-08-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
