# Generated by Django 4.1.7 on 2026-08-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
