# Generated by Django 4.1.7 on 2026-08-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Picked', 'Picked Up - Courier Assigned'), ('Returned', 'Returned to Warehouse'), ('Refunded', 'Refunded'), ('Rejected', 'Rejected')], default='Requested,choices=STATUS_CHOICES', max_length=20),
        ),
    ]
