# Generated by Django 4.1.7 on 2026-09-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
